#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
    docker {
        image 'maven:3.6.3-1'
        label 'maven'
    }
}
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
    }
}